name: QJsonStruct build matrix - cmake

on: 
  push:

jobs:
  build:
    strategy:
      matrix:
        qt_version: [5.15.0]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86, x64]
        include: 
          - platform: windows-latest
            arch: x86
            qtarch: win32_msvc2017
          - platform: windows-latest
            arch: x64
            qtarch: win64_msvc2017_64
          - platform: ubuntu-latest
            arch: x64
        exclude:
          - platform: ubuntu-latest
            arch: x86
          - platform: macos-latest
            arch: x86
      fail-fast: false
        
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checking out sources
        uses: actions/checkout@master
# =========================================================================================================
      - name: Install MSVC compiler
        if: matrix.platform == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
        with: 
          # 14.1 is for vs2017, 14.2 is vs2019, following the upstream vcpkg build from Qv2ray-deps repo
          toolset: 14.2
          arch: ${{ matrix.arch }}
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: QtCache-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.qt_version }}
      - name: Installing Qt - ${{ matrix.arch }}
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_version }}
          arch: ${{ matrix.qtarch }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
# =========================================================================================================
      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build .
      - name: Run
        shell: bash
        run: |
          cd ./build/
          ctest . -VV
